#Configuração do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5433/TREINAMENTO-API
spring.datasource.username=postgres
spring.datasource.password=#abc123#

#Configuração do hibernate
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size = 5
spring.datasource.hikari.minimum-idle = 3
spring.datasource.hikari.idle-timeout = 10000