spring.datasource.url=jdbc:postgresql://localhost:5432/TREINAMENTO-API
spring.datasource.username=postgres
spring.datasource.password=#abc123#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect